### ISSUE TITLE
error when install 

### ISSUE THREAD

**Issue by RapiDic3** [tiagorlampert/CHAOS#35] opened 2019-03-12 13:41 UTC
hi

im getting this error on kali 2019.1-vbox i386

go install github.com/kbinani/screenshot && go install github.com/lxn/win
# github.com/gen2brain/shm
go/src/github.com/gen2brain/shm/shm_linux_386.go:9:14: undefined: syscall.SYS_SHMAT
go/src/github.com/gen2brain/shm/shm_linux_386.go:10:14: undefined: syscall.SYS_SHMCTL
go/src/github.com/gen2brain/shm/shm_linux_386.go:11:14: undefined: syscall.SYS_SHMDT
go/src/github.com/gen2brain/shm/shm_linux_386.go:12:14: undefined: syscall.SYS_SHMGET

**Comment by tiagorlampert** [comment] 2019-03-28 14:31
Hello, sorry for delay.
That's weird, could you try again? I've updated CHAOS to a new release, the requirements are been changed.
Follow [How To Install](https://github.com/tiagorlampert/CHAOS#how-to-install)

**Comment by RapiDic3** [comment] 2019-03-31 18:30
still the same error

im going to try kali iso in vbox and try that way..

go install github.com/kbinani/screenshot

github.com/gen2brain/shm
../go/src/github.com/gen2brain/shm/shm_linux_386.go:9:14: undefined: syscall.SYS_SHMAT
../go/src/github.com/gen2brain/shm/shm_linux_386.go:10:14: undefined: syscall.SYS_SHMCTL
../go/src/github.com/gen2brain/shm/shm_linux_386.go:11:14: undefined: syscall.SYS_SHMDT
../go/src/github.com/gen2brain/shm/shm_linux_386.go:12:14: undefined: syscall.SYS_SHMGET

**Comment by tiagorlampert** [comment] 2019-04-01 14:00
I'm using Kali x64 Rolling Release Updated.
Maybe the problem is if your OS is x86, i'm not sure, but there's a problem with your OS.
Could you try on Kali x64?

**Comment by RapiDic3** [comment] 2019-04-02 14:52
i skipped this step and it works... 
go install github.com/kbinani/screenshot

i will try on 64 today and report back.. thanks

**Comment by tiagorlampert** [comment] 2019-05-04 12:24
Hello,
I've think this issue has been solved, i'm closing it.

**Closed** 2019-05-04 12:25 UTC
